;              
CREATE USER IF NOT EXISTS SA SALT '5ef9da2dc5b33b44' HASH '91bed40738cd39ca6458914dd64745e73276677aac7126a28d0e27a08dbf92e4' ADMIN;            
CREATE SEQUENCE PUBLIC.SEQ_LOCATIONS START WITH 1;             
CREATE SEQUENCE PUBLIC.SEQ_DEPARTMENTS START WITH 1;           
CREATE SEQUENCE PUBLIC.SEQ_EMPLOYEES START WITH 1;             
CREATE SEQUENCE PUBLIC.SEQ_REGIONS START WITH 1;               
CREATE MEMORY TABLE PUBLIC.COUNTRIES(
    COUNTRYISOCODE VARCHAR2(2) NOT NULL,
    COUNTRYNAME VARCHAR2(40) DEFAULT NULL,
    REGIONID INT DEFAULT NULL
);     
ALTER TABLE PUBLIC.COUNTRIES ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(COUNTRYISOCODE);   
-- 25 +/- SELECT COUNT(*) FROM PUBLIC.COUNTRIES;               
CREATE MEMORY TABLE PUBLIC.DEPARTMENTS(
    DEPARTMENTID INT NOT NULL,
    DEPARTMENTNAME VARCHAR(30) DEFAULT NULL,
    MANAGERID INT DEFAULT NULL,
    LOCATIONID INT DEFAULT NULL
);         
ALTER TABLE PUBLIC.DEPARTMENTS ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(DEPARTMENTID);   
-- 27 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTMENTS;             
CREATE MEMORY TABLE PUBLIC.EMPLOYEES(
    EMPLOYEEID INT NOT NULL,
    FIRSTNAME VARCHAR(20) DEFAULT NULL,
    LASTNAME VARCHAR(25) DEFAULT NULL,
    EMAIL VARCHAR(25) DEFAULT NULL,
    PHONENUMBER VARCHAR(20) DEFAULT NULL,
    HIREDATE DATETIME DEFAULT NULL,
    JOBCODE VARCHAR(10) DEFAULT NULL,
    SALARY DOUBLE DEFAULT NULL,
    COMMISSIONPERCENTAGE DOUBLE DEFAULT NULL,
    MANAGERID INT DEFAULT NULL,
    DEPARTMENTID INT DEFAULT NULL
);   
ALTER TABLE PUBLIC.EMPLOYEES ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(EMPLOYEEID);       
-- 50 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEES;               
CREATE MEMORY TABLE PUBLIC.JOB_HISTORY(
    EMPLOYEEID INT NOT NULL,
    STARTDATE DATETIME DEFAULT NULL,
    ENDDATE DATETIME DEFAULT NULL,
    JOBCODE VARCHAR(10) NOT NULL,
    DEPARTMENTID INT DEFAULT NULL
);            
ALTER TABLE PUBLIC.JOB_HISTORY ADD CONSTRAINT PUBLIC.CONSTRAINT_95 PRIMARY KEY(EMPLOYEEID, JOBCODE);           
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.JOB_HISTORY;             
CREATE MEMORY TABLE PUBLIC.JOBS(
    JOBCODE VARCHAR(10) NOT NULL,
    JOBTITLE VARCHAR(35) DEFAULT NULL,
    MINSALARY INT DEFAULT NULL,
    MAXSALARY INT DEFAULT NULL
);    
ALTER TABLE PUBLIC.JOBS ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(JOBCODE);               
-- 19 +/- SELECT COUNT(*) FROM PUBLIC.JOBS;    
CREATE MEMORY TABLE PUBLIC.LOCATIONS(
    LOCATIONID INT NOT NULL,
    STREETADDRESS VARCHAR(40) DEFAULT NULL,
    POSTALCODE VARCHAR(12) DEFAULT NULL,
    CITY VARCHAR(30) DEFAULT NULL,
    STATEPROVINCE VARCHAR(25) DEFAULT NULL,
    COUNTRYISOCODE VARCHAR(2) DEFAULT NULL
);           
ALTER TABLE PUBLIC.LOCATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(LOCATIONID);       
-- 23 +/- SELECT COUNT(*) FROM PUBLIC.LOCATIONS;               
CREATE MEMORY TABLE PUBLIC.REGIONS(
    REGIONID INT NOT NULL,
    REGIONNAME VARCHAR(25) DEFAULT NULL
);      
ALTER TABLE PUBLIC.REGIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(REGIONID);           
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.REGIONS;  
CREATE MEMORY TABLE PUBLIC.USERS(
    USER_ID VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PASSWD VARCHAR(255),
    ACTIVATED BOOLEAN DEFAULT FALSE NOT NULL,
    DISABLED BOOLEAN DEFAULT FALSE NOT NULL
);         
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4D PRIMARY KEY(USER_ID);             
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
ALTER TABLE PUBLIC.JOB_HISTORY ADD CONSTRAINT PUBLIC.FK_JOB_HISTORY_DEPARTMENTID FOREIGN KEY(DEPARTMENTID) REFERENCES PUBLIC.DEPARTMENTS(DEPARTMENTID) NOCHECK;
ALTER TABLE PUBLIC.EMPLOYEES ADD CONSTRAINT PUBLIC.FK_EMPLOYEE_DEPARTMENTID FOREIGN KEY(DEPARTMENTID) REFERENCES PUBLIC.DEPARTMENTS(DEPARTMENTID) NOCHECK;     
ALTER TABLE PUBLIC.LOCATIONS ADD CONSTRAINT PUBLIC.FK_LOCATION_COUNTRYISOCODE FOREIGN KEY(COUNTRYISOCODE) REFERENCES PUBLIC.COUNTRIES(COUNTRYISOCODE) NOCHECK; 
ALTER TABLE PUBLIC.JOB_HISTORY ADD CONSTRAINT PUBLIC.FK_JOB_HISTORY_JOBCODE FOREIGN KEY(JOBCODE) REFERENCES PUBLIC.JOBS(JOBCODE) NOCHECK;      
ALTER TABLE PUBLIC.EMPLOYEES ADD CONSTRAINT PUBLIC.FK_EMPLOYEE_JOBCODE FOREIGN KEY(JOBCODE) REFERENCES PUBLIC.JOBS(JOBCODE) NOCHECK;           
ALTER TABLE PUBLIC.COUNTRIES ADD CONSTRAINT PUBLIC.FK_COUNTRY_REGIONID FOREIGN KEY(REGIONID) REFERENCES PUBLIC.REGIONS(REGIONID) NOCHECK;      
